version: 2.1
orbs:
  sumologic: circleci/sumologic@1
  common: timebyping/common@2
parameters:
  executor-tag:
    type: string
    default: lts-browsers
    description: |
      Pick a specific circleci/node image variant: https://hub.docker.com/r/cimg/node/tags
jobs:
  lint:
    working_directory: /tmp/src
    docker:
      - image: cimg/node:<< pipeline.parameters.executor-tag >>
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - checkout
      - run: yarn
      - run: yarn run lint
  build:
    working_directory: /tmp/src
    docker:
      - image: cimg/node:<< pipeline.parameters.executor-tag >>
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - checkout
      - run: yarn
      - run: yarn run build
  test_spec:
    working_directory: /tmp/src
    docker:
      - image: cimg/node:<< pipeline.parameters.executor-tag >>
    resource_class: xlarge
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - checkout
      - run: yarn
      - run: yarn run test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ./test-results
          destination: test-results
      - common/coverage
workflows:
  developer-branch:
    when:
      not:
        equal:
          - << pipeline.git.branch >>
          - main
    jobs:
      - sumologic/workflow-collector:
          context:
            - SUMOLOGIC
      - common/pr-lint:
          context:
            - GITHUB
      - lint:
          context:
            - NPM
      - build:
          context:
            - NPM
      - test_spec:
          name: unit tests
          context:
            - NPM
            - SLACK
  main-branch:
    when:
      equal:
        - << pipeline.git.branch >>
        - main
    jobs:
      - sumologic/workflow-collector:
          context:
            - SUMOLOGIC
      - lint:
          context:
            - NPM
      - build:
          context:
            - NPM
      - test_spec:
          name: unit tests
          context:
            - NPM
            - SLACK
      - common/semantic-release:
          name: semantic release
          requires:
            - lint
            - build
            - unit tests
          context:
            - GITHUB
            - NPM
            - SLACK
          executor-tag: << pipeline.parameters.executor-tag >>
          package-manager: yarn
          dry-run: false
          github: true
          npm: true
